phrase = "DipsansAcademy"
print("This is a string")
print('This'+ phrase+ "")
print(phrase.upper())
print(phrase.lower())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[1])
print(phrase[4])
print(phrase.index("A"))
print(phrase.replace("Dipsans","kadariya"))